### ISSUE TITLE
Design Help - Colors

### ISSUE THREAD

**Issue by OtacilioN** [ThiagoAugustoSM/arduino-buzzer-code-generator#3]
If you are a designer you can help refactoring the colors of the website (and the notes), and also refactoring the spacing and location of the things on the website.

**Comment by OtacilioN** [comment]
@ThiagoAugustoSM the scripts are looking for "Hacktoberfest" label to show users repositories to contribute.

**Comment by mluisas** [comment]
Working with colors! @ThiagoAugustoSM

**Comment by ThiagoAugustoSM** [comment]
Issue solved on PR #6.
