### ISSUE TITLE
Copy function not working

### ISSUE THREAD

**Issue by ThiagoAugustoSM** [ThiagoAugustoSM/arduino-buzzer-code-generator#9]
## Specification
An error is fired when the copy button is clicked on the [index.html](https://github.com/ThiagoAugustoSM/arduino-buzzer-code-generator/blob/master/index.html) file.

## Work on it
If you want to work on it, comment and tell the others that you are going to do that.

**Comment by bethuxs** [comment]
Checking this bug

**Comment by anmol8399** [comment]
I am taking this

**Comment by ThiagoAugustoSM** [comment]
Solved on #11 .
